services:
  go-webhook-receive:
    build:
      context: ./
      dockerfile: receive.Dockerfile
    container_name: go-webhook-receive
    ports:
      - "9101:8080"
  go-webhook-send:
    build:
      context: ./
      dockerfile: send.Dockerfile
    container_name: go-webhook-send
    ports:
      - "9001:8080"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
