name: Go-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - run: go test ./tests -v
      # - name: Install dependencies
      #   run: make deps
      # - name: Build Send Server
      #   run: CGO_ENABLED=0 go build -o ./build/send ./cmd/send
      # - name: Build Receive Server
      #   run: CGO_ENABLED=0 go build -o ./build/receive ./cmd/receive
      # - name: Test with the Go CLI
      #   run: make test
