name: Go-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Build Receive Server
        run: make receive-build
      - name: Build Send Server
        run: make send-build
      - name: Run tests
        run: make test
